name: Push Jobe to Aliyun

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Aliyun ACR
      uses: azure/docker-login@v1
      with:
        login-server: crpi-cyu7l7j5wn3960kl.cn-beijing.personal.cr.aliyuncs.com
        username: ${{ secrets.ALIVER_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    - name: Build and push
      run: |
        # 拉取官方原镜像
        docker pull trampgeek/jobeinabox:latest
        # 重新打标签
        docker tag trampgeek/jobeinabox:latest crpi-cyu7l7j5wn3960kl.cn-beijing.personal.cr.aliyuncs.com/my-moodle/jobe:latest
        # 推送到阿里云
        docker push crpi-cyu7l7j5wn3960kl.cn-beijing.personal.cr.aliyuncs.com/my-moodle/jobe:latest
